### ISSUE TITLE
Any example about response, Http Code and more ?

### ISSUE THREAD

**Issue by vschoener** [guzzle/command#38]
Hi,

There is no documentation how to get the response, http code and more. Is there possible to add it ?

**Comment by zcharleshebert** [comment]
+1

**Comment by jeremeamia** [comment]
Yeah, it could use some docs, but the basic gist is that since [you provide the response-to-result transformer logic](https://github.com/guzzle/command/blob/master/src/ServiceClient.php#L50), you can put anything from the response into your result objects, however you like. The [transformer gets a reference to the response, request, and command](https://github.com/guzzle/command/blob/master/src/ServiceClient.php#L215) in order to provide the most flexibility.
